//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion
    {
        public int idcalificacion { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<short> unidad { get; set; }
        public int idmatricula { get; set; }
        [JsonIgnore]
        public virtual matricula matricula { get; set; }
    }
}
