//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumnoes { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<calificacion> calificacions { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<matricula> matriculas { get; set; }
        public virtual DbSet<maquinaria> maquinarias { get; set; }
        public virtual DbSet<tipoBeca> tipoBecas { get; set; }
    }
}
