//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoBeca
    {
        public int idTipoBecas { get; set; }
        public string nombre { get; set; }
        public string requisitos_especificos { get; set; }
        public int porcentaje_matricula { get; set; }
        public string tipo_calificacion_necesaria { get; set; }
        public string documentos_respaldo { get; set; }
    }
}
